### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by shazow** [Lukasa/mkcert.org#1]
Some thoughts:
- Looks fine already. :) Don't worry too much.
- I'd lean towards an easily-skimmable vertical flow format than multiple horizontal columns that requires both horizontal and vertical skimming. Especially for technical content.
- http://commonmark.org/ is a nice recent example to borrow inspiration from. http://caskroom.io/ is another.
- I'd almost lean towards making it a mirror of the project's README.

**Comment by Lukasa** [comment]
M'kay, so I think the narrow vertical flow is a good idea, I've switched to that now. Looks better: thanks!

I'll probably work on the 'usage' section a bit more to bring it closer to the README.

**Comment by Lukasa** [comment]
Alright, done. =)
